### ISSUE TITLE
Deprecation Warning `#deliver`

### ISSUE THREAD

**Issue by sled** [at-point/mote_sms#5]
Just noticed in the log:

`DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job. (called from deliver at /Users/xxx/.rvm/gems/ruby-2.2.2/bundler/gems/mote_sms-bf78de17e24a/lib/mote_sms/transports/action_mailer_transport.rb:45)`

**Comment by lwe** [comment]
^^ upgrade mote_sms this is already fixed, you are somehow using an unversioned install from GH commit bf78de17e24a
