### ISSUE TITLE
Review HttpClient

### ISSUE THREAD

**Issue by lwe** [at-point/mote_sms#8]
Hey @lgavillet can you please review the following changes:

https://github.com/at-point/mote_sms/compare/c8b652a93df5879512177a6afaf2da413dfbcd42...master
- [x] Removal of SslTransport
- [x] Introduction of HttpClient class instead, which is a small wrapper
- [x] Handles overriding of fingerprint SHA1 using ENV changes, so we don't need to release a new gem
- [x] Use SHA1 as fingerprint
- [ ] How to handle overriding or adding CA certificates using ENV too, any proposals?

**Comment by lgavillet** [comment]
For the CA, really dummy approach: Why wouldn't we pass the cert store in the initializer/config, like: 

```ruby
MoteSMS.transport = MoteSMS::SwisscomTransport.new 'https://api.swisscom.com/', ENV['SMS_API_KEY'], nil, 
                                                   proxy_address: ENV['SWISSCOM_PROXY_HOST'], 
                                                   proxy_port: ENV['SWISSCOM_PROXY_PORT']
                                                   cert_store: OpenSSL::X509::Store.new.tap { |store| Dir["#{CERTS_PATH}/*CA.pem"].each { |c| store.add_file c } }
```

**Comment by lgavillet** [comment]
Or otherwise, yep, just an ENV path to the cert folder, egal...

**Comment by lwe** [comment]
Either way not yet too happy with this, as all options need to be passed from the transport to the client.

**Comment by lgavillet** [comment]
This means you wanna go for a MoteSms v2.0 with breakable changes and start from scratch? :D

**Comment by lwe** [comment]
Haha, no 😄
